import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-blue-600 text-center mt-56 text-7xl font-semibold">Facebook</h1>
    </div>
  );
}
