import Head from "next/head";
import { getSession } from "next-auth/react";
import Login from "./login";
import Header from "../components/header";
import Sidebar from "../components/sidebar";

export default function Home({ session }) {
  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Left-Sidebar */}
      <Sidebar />
      {/* Post section */}
      {/* Right-Sidebar */}
    </div>
  );
}

export async function getServerSideProps(context) {
  // Get the user
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
